// Shared constants for the NeedleScript playground UI

import lorenzRaw        from '../examples/lorenz-attractor.ns?raw';
import meanderRaw       from '../examples/meandering-spiral.ns?raw';
import snowflakeRaw     from '../examples/snowflake.ns?raw';
import orbitsRaw        from '../examples/threaded-orbits.ns?raw';
import waveformsRaw     from '../examples/waveforms.ns?raw';
import fillRaw          from '../examples/fill.ns?raw';
import linesRaw         from '../examples/lines.ns?raw';
import vennRaw          from '../examples/venn.ns?raw';

export const THREADS: string[] = [
  '#C8472F', // 0 — red
  '#31604F', // 1 — forest
  '#3A4E8C', // 2 — blue
  '#D9A441', // 3 — gold
  '#8C4A6B', // 4 — mauve
  '#2B2B2B', // 5 — black
  '#5E8F8C', // 6 — teal
  '#B8651B', // 7 — amber
];

export interface HoopConfig {
  id: string;
  label: string;
  widthMM: number;
  heightMM: number;
  shape: 'circle' | 'oval' | 'rectangle';
}

export const HOOPS: HoopConfig[] = [
  { id: 'round-100',    label: '100 mm round',    widthMM: 100, heightMM: 100, shape: 'circle'    },
  { id: 'round-130',    label: '130 mm round',    widthMM: 130, heightMM: 130, shape: 'circle'    },
  { id: 'round-150',    label: '150 mm round',    widthMM: 150, heightMM: 150, shape: 'circle'    },
  { id: 'round-200',    label: '200 mm round',    widthMM: 200, heightMM: 200, shape: 'circle'    },
  { id: 'oval-120x75',  label: '120×75 mm oval',  widthMM: 120, heightMM:  75, shape: 'oval'      },
  { id: 'oval-150x100', label: '150×100 mm oval', widthMM: 150, heightMM: 100, shape: 'oval'      },
  { id: 'rect-100',     label: '100×100 mm',      widthMM: 100, heightMM: 100, shape: 'rectangle' },
  { id: 'rect-180x130', label: '180×130 mm',      widthMM: 180, heightMM: 130, shape: 'rectangle' },
];

export const DEFAULT_HOOP: HoopConfig = HOOPS[0];

export const EXAMPLES: Record<string, string> = {
  'bloom — rose of circles': [
    '; twelve overlapping circles make a rose.',
    '; the small fd between circles spreads their',
    '; start points so no hole is punched twice',
    'stitchlen 2.2',
    'repeat 12 [',
    '  repeat 36 [ fd 3.4 rt 10 ]',
    '  rt 30 fd 0.8',
    ']',
  ].join('\n'),
  'wreath — leaf procedure': [
    '; a leaf is two 90-degree arcs',
    'to leaf :s',
    '  repeat 2 [',
    '    repeat 30 [ fd :s rt 3 ]',
    '    rt 90',
    '  ]',
    'end',
    '',
    'repeat 8 [ leaf 1.2 rt 45 fd 0.6 ]',
  ].join('\n'),
  'wander — bounded random walk': [
    '; a random walk that turns back at the edge.',
    '; change the seed for a new design.',
    'seed 11',
    'stitchlen 2',
    'repeat 420 [',
    '  fd 2.6',
    '  rt random 70 - 35',
    '  if sqrt ( xcor * xcor + ycor * ycor ) > 36 [',
    '    rt 140 + random 80',
    '  ]',
    ']',
  ].join('\n'),
  'star — satin stitch': [
    '; satin makes a zigzag column 3 mm wide',
    'up setxy -6 -21 down',
    'satin 3',
    'repeat 5 [ fd 42 rt 144 ]',
    'satin 0',
  ].join('\n'),
  'badge — tatami fill, bean border': [
    '; trace a boundary between beginfill/endfill,',
    '; then retrace it with a bold triple-run line',
    'fillangle 30',
    'up setxy -26 -15 down',
    'beginfill',
    '  repeat 6 [ fd 30 rt 60 ]',
    'endfill',
    '',
    'color 3',
    'bean 3',
    'repeat 6 [ fd 30 rt 60 ]',
    'bean 1',
  ].join('\n'),
  'sampler — four line weights': [
    '; running, bean, satin, blanket',
    'stitchlen 2.5',
    'up setxy -30 27 seth 90 down',
    'fd 60',
    'up setxy -30 10 seth 90 down',
    'bean 3 fd 60 bean 1',
    'up setxy -30 -8 seth 90 down',
    'satin 2.5 fd 60 satin 0',
    'up setxy -30 -24 seth 90 down',
    'estitch 4 fd 60 estitch 0',
  ].join('\n'),
  'waves — sashiko rows': [
    '; rows of running-stitch scallops',
    'stitchlen 2.5',
    'to wave',
    '  repeat 3 [',
    '    repeat 18 [ fd 1.1 rt 10 ]',
    '    repeat 18 [ fd 1.1 lt 10 ]',
    '  ]',
    'end',
    '',
    'repeat 4 [',
    '  up setxy 38 repcount * 16 - 40 seth 180 down',
    '  wave',
    ']',
  ].join('\n'),
  'tree — recursion, sewn out and back': [
    '; branches retrace themselves (bk) so the',
    '; whole tree sews as one unbroken thread',
    'to branch :len',
    '  if :len < 5 [ fd :len bk :len ]',
    '  else [',
    '    fd :len / 2',
    '    lt 28 branch :len * 0.62 rt 28',
    '    fd :len / 4',
    '    rt 32 branch :len * 0.62 lt 32',
    '    fd :len / 4',
    '    bk :len',
    '  ]',
    'end',
    '',
    'up setxy 0 -27 down',
    'branch 34',
  ].join('\n'),
  'fern — push/pop branching': [
    '; push saves the needle, pop jumps back —',
    '; branches need no sewing back. exit leaves',
    '; the procedure early on the smallest tips.',
    'to frond :len',
    '  if :len < 3 [ fd :len exit ]',
    '  fd :len / 3',
    '  push lt 40 frond :len * 0.5 pop',
    '  push rt 40 frond :len * 0.5 pop',
    '  frond :len * 0.62',
    'end',
    '',
    'stitchlen 1.8',
    'up setxy 0 -34 down',
    'frond 42',
  ].join('\n'),
  'flow — noise field strands': [
    '; strands drift through a smooth noise field.',
    '; exit stops a strand at the boundary circle.',
    'to strand',
    '  repeat 90 [',
    '    seth ( noise2 xcor / 16 ycor / 16 ) * 720',
    '    fd 1.8',
    '    if distance 0 0 > 40 [ exit ]',
    '  ]',
    'end',
    '',
    'seed 9',
    'stitchlen 2',
    'repeat 14 [',
    '  up setxy random 64 - 32 random 64 - 32 down',
    '  strand',
    '  trim',
    ']',
  ].join('\n'),
  'shell — while + arc': [
    '; arcs of growing radius until the edge.',
    '; print traces the radius in the console.',
    'up setxy -12 14 seth 90 down',
    'make "r 2.2',
    'while :r < 26 [',
    '  arc 100 :r',
    '  make "r :r * 1.16',
    '  print "radius :r',
    ']',
  ].join('\n'),
  'patch — knit-ready badge': [
    '; the fabric preset adds pull compensation and',
    '; automatic underlay. the fill is inset so the',
    '; satin border covers its edge; that border',
    '; still measures ~4 layers of thread — fine for',
    '; a badge, so the limit is raised knowingly.',
    '; toggle "density" on the stage to see it.',
    'fabric "knit',
    'maxdensity 4.5',
    'fillangle 25',
    'up setxy -12.8 -14.8 down',
    'beginfill',
    '  repeat 4 [ fd 16 arc 90 4.8 ]',
    'endfill',
    '',
    'color 0',
    'up setxy -14 -16 down',
    'satin 3',
    'repeat 4 [ fd 16 arc 90 6 ]',
    'satin 0',
  ].join('\n'),
  'meadow — modern syntax tour': [
    '// meadow — a tour of the modern NeedleScript syntax.',
    '//',
    '// let / assignment / +=, call parens & commas, def/return, recursion,',
    '// else-if, keyword for (with and without step), %, !, ==, true/false,',
    '// closed strings, and // and # comments — freely mixed with classic',
    '// Logo style, which is the intended idiom: prefix words for movement,',
    '// call syntax for expressions.',
    '',
    'fabric "knit"            // preset: pull comp, auto underlay, density cap',
    'seed 11                  # same seed, same meadow — # comments work too',
    'stitchlen 2.2',
    'autotrim 6',
    '',
    'let debug = false        // flip to true for pins + console output',
    '',
    '// ---- helper reporters ----------------------------------------',
    '',
    'def clamp(v, lo, hi) [',
    '  return min(hi, max(lo, v))',
    ']',
    '',
    'def len2(x, y) [         // distance of a *point* from the origin',
    '  return sqrt(x * x + y * y)',
    ']',
    '',
    'def inside(x, y) [       // call parens end the old "trailing operator',
    '  return len2(x, y) < 31 // gets absorbed" footgun',
    ']',
    '',
    '// ---- procedures ------------------------------------------------',
    '',
    '// recursive grass sprig — bare `return` is `exit`',
    'def sprig(depth, seg) [  // nb: "step" is reserved, hence "seg"',
    '  if depth == 0 [ return ]',
    '  fd seg',
    '  push',
    '    lt 35',
    '    sprig(depth - 1, seg * 0.62)',
    '  pop',
    '  push',
    '    rt 30',
    '    sprig(depth - 1, seg * 0.62)',
    '  pop',
    '  bk seg                 // sew back down the trunk',
    ']',
    '',
    'def leaf(size) [         // tatami-filled leaf',
    '  beginfill',
    '    repeat 2 [ arc 90 size rt 90 ]',
    '  endfill',
    ']',
    '',
    'def bloom(size, kind) [',
    '  if kind == 0 [',
    '    // daisy: six petal outlines around a center ring.',
    '    // the small fd spreads the petal bases so no',
    '    // hole at the hub is punched twice',
    '    repeat 6 [',
    '      repeat 2 [ arc 90 size rt 90 ]',
    '      rt 60 fd 0.9',
    '    ]',
    '    arc 360 clamp(size / 3, 1, 1.8)',
    '  ] else if kind == 1 [',
    '    // unfurling spiral',
    '    bean 3',
    '    for t = 1 to 4 [ arc 130 t * 0.7 ]',
    '    bean 1',
    '  ] else [',
    '    // seed-head burst — spokes drift around the hub',
    '    repeat 8 [ fd size + 1.5  bk size + 1.5  rt 45 fd 0.8 ]',
    '  ]',
    ']',
    '',
    '// ---- ground ----------------------------------------------------',
    '',
    'color 1',
    'fillangle 20',
    'up setxy(-8, -33) seth -25 down',
    'leaf(8)',
    'up setxy(8, -34) seth 20 down',
    'leaf(7)',
    'trim',
    '',
    'for gx = -20 to 20 step 10 [             // keyword for, explicit step',
    '  up',
    '  setxy(gx, -33 + random(3))',
    '  seth (noise(gx / 9) - 0.5) * 40        // space before ( = grouping',
    '  down',
    '  sprig(3, 3.5)',
    '  trim',
    ']',
    '',
    '// ---- flowers ---------------------------------------------------',
    '',
    'for i = 1 to 7 [                         // default step = 1',
    '  // rejection-sample a position inside the meadow',
    '  let x = random(64) - 32',
    '  let y = random(44) - 14',
    '  let tries = 0',
    '  while !inside(x, y) [                  // ! on a reporter call',
    '    x = random(64) - 32                  // bare reassignment',
    '    y = random(44) - 14',
    '    tries += 1',
    '    assert tries < 99                    // geometric invariant guard',
    '  ]',
    '',
    '  color 2 + i % 3                        // cycle threads 2, 3, 4',
    '  up setxy(x, y) seth random(360) down',
    '',
    '  let kind = floor(random(3))',
    '  if debug [ mark  print "flower" kind ] // closed-quote print label',
    '  bloom(clamp(2.5 + random(3), 2.5, 5), kind)',
    '  trim',
    ']',
    '',
    '// ---- border ----------------------------------------------------',
    '',
    'color 5',
    'satin 2.2',
    'up setxy(0, 42) seth 90 down',
    'arc 360 42                               // classic Logo, untouched',
    'satin 0',
    'trim',
  ].join('\n'),
  'echo — record & replay with lists': [
    '// record a noisy walk, then re-sew it mirrored, echoed in shuffled',
    '// palette colours — a tour of the list features (RFC-2):',
    '// literals, append/pos recording, for-in, indexing, setpos,',
    '// and the seeded shuffle randomness.',
    '',
    'seed 5',
    'let palette = [2, 3, 5, 7]',
    'let path = []',
    '',
    'up setxy(-26, 24) down',
    'repeat 70 [',
    '  seth(noise2(xcor / 8, ycor / 8) * 360)',
    '  fd 1.6',
    '  append(path, pos())     // pos() is [xcor, ycor]',
    ']',
    'trim',
    '',
    'let off = 0',
    'for c in shuffle(palette) [',
    '  color c',
    '  up setpos([-first(path)[0] + off, first(path)[1]]) down',
    '  for p in path [',
    '    setpos([-p[0] + off, p[1]])  // mirror across the y axis',
    '  ]',
    '  trim',
    '  off += 2.5                     // drift each echo to the right',
    ']',
    'print "points" len(path)',
  ].join('\n'),
  'shatter — generative voronoi': [
    '// shatter — Voronoi tiles with inset outlines and flow-field',
    '// hatching inside: a tour of the generative math (RFC-3).',
    '// scatter → voronoi → offsetpath → resample → sewpath compose',
    '// because a point is [x, y], a path is a list of points, and a',
    '// region is a closed path.',
    'seed 4',
    'let pts = scatter(9)              // Poisson-disc over the sewable field',
    'let tiles = voronoi(pts)',
    '',
    'color 1',
    'for cell in tiles [',
    '  for ring in offsetpath(cell, -0.9) [   // may be 0, 1, or 2+ rings',
    '    sewpath(resample(ring, 2.2))',
    '    setpos(ring[0])                      // close the outline',
    '  ]',
    '  trim',
    ']',
    '',
    'color 2',
    'for cell in tiles [',
    '  let c = centroid(cell)',
    '  if inpath(c, cell) [             // concave cells can evict their centroid',
    '    up setpos(c) down',
    '    repeat 25 [                    // walk the noise field until we leave the cell',
    '      seth(snoise2(xcor / 14, ycor / 14) * 180)',
    '      let nxt = vadd(pos(), vfromheading(heading, 1.8))',
    '      if !inpath(nxt, cell) [ break ]',
      '      fd 1.8',
      '    ]',
      '    trim',
      '  ]',
      ']',
  ].join('\n'),
};

// Examples loaded from .ns files in /examples — shown in a separate group
// in the dropdown. Keys are the short display names used as labels and as
// lookup keys in App.tsx.
export const GALLERY_EXAMPLES: Record<string, string> = {
  'lorenz':     lorenzRaw,
  'meander':    meanderRaw,
  'snowflake':  snowflakeRaw,
  'orbits':     orbitsRaw,
  'waveforms':  waveformsRaw,
  'fill':       fillRaw,
  'lines':      linesRaw,
  'venn':       vennRaw,
};
